using System.Collections.Generic;

namespace Halcyon.FirstWeather
{
    public static class SliceStory
    {
        static StoryChoice C(string label, string effect) { return new StoryChoice(label, effect); }
        static StoryPage P(string who, string text, params StoryChoice[] choices) { return new StoryPage(who, text, choices); }
        public static List<StoryPage> Get(string key, SliceState s)
        {
            switch (key)
            {
                case "morning1": return new List<StoryPage> {
                    P("MOLLY", "The first morning of the first year. Someone has polished the residence door until Molly can see her own worried face in the brass. Inside, her suitcase waits on the bed. Outside, a boat leaves a mint-colored seam in the canal. For once, the day belongs to her before it belongs to anybody else."),
                    P("A ROOM OF YOUR OWN", "The room is beautiful in the impersonal way of a room prepared for anyone. Molly puts her father's photograph face down while she unpacks, then feels ridiculous and stands it up again. There is space on the sill for one thing from home. Something that will tell her, tomorrow, that she has already arrived.", C("A fern cutting from home", "decor:fern"), C("A small brass boat", "decor:boat"), C("A postcard of the old city", "decor:postcard")),
                    P("ALARIC · VOICE MESSAGE", "'The first lift is always the worst,' her father says. She can hear the smile he puts on for difficult mornings. 'Your grandmother said that about boats. You needn't give a speech, you know. Just find something you're curious about.' A pause. 'And eat breakfast, please. Leadership can wait until after toast.'"),
                    P("MOLLY", "He has remembered the toast. He has not remembered that telling her she needn't give a speech makes her imagine giving one. Below the message light sits her familiar Vapeur case. The routine helps take an edge off some mornings. It has never made her somebody else, or made the day entirely predictable.", C("Follow the familiar routine  ·  Pressure −6", "routine"), C("Put it away for this morning", "noroutine")),
                    P("YOUR FIRST TIMETABLE", "The little barometer measures Pressure: how demanding the day feels to Molly. Lower numbers mean more room to respond. It is a fictional game measure, not a diagnosis. Today, class leaves time for two activities. Preparation, rest, and company each offer something different. Their effects are shown before you choose; they will still matter tomorrow."),
                    P("MOLLY", "A bell travels through the open window. On the landing, someone is practicing a name under their breath, and Molly realizes it is probably their own introduction. She laughs quietly, relieved by the ordinary sound. All over Halcyon, students are making this journey for the first time. She closes her suitcase and opens the city map.")
                };
                case "class1": return new List<StoryPage> {
                    P("HALCYON ACADEMY", "The Academy smells of new varnish over very old stone. A hundred years of balcony iron has been worked into its gallery. No Ward could have built this place alone. Their workshops, clinics, libraries, and apprenticeships trained the people who built it; this is the first time they have sent their students to learn together."),
                    P("DR. VALE", "'Welcome to an experiment,' the lecturer says. 'Not all of you are engineers. Good. Not all of you are artists. Good. This city already has remarkable specialists. What it needs is people who can ask one another better questions.' On the table, a little brass model of the Cloche catches the morning light."),
                    P("MOLLY", "For fifty years the Cloche has sheltered the city. Her grandfather built the dome; her father learned to gather power from storms moving across it. The lamps, warm homes, and growing houses make that work visible everywhere. Molly loves the city he helped make. She wishes loving it felt less like having to explain him."),
                    P("CHOOSE A MENTOR", "There are two open seats at the demonstration table. At one, a tutor measures the water passing through a model canal. At the other, a tutor asks who will maintain the canal after the designers go home. You can learn from both eventually. For this first assignment, whose question will you begin with?", C("Circulation  ·  how the system works", "mentor:circulation"), C("Civic ecology  ·  who it works for", "mentor:ecology")),
                    P("YOUR MENTOR", s.mentor == "circulation" ? "'Supply is finite,' your tutor says, tipping six brass measures into a reservoir. 'A good design does not pretend otherwise. But a pipe tells us only what passes through it. Someone must tell us what the water is needed for.' Molly draws three branches in her notebook. It is pleasant to be asked to look closely instead of perform." : "'A garden is also an agreement,' your tutor says. 'Someone waters it, someone eats from it, someone fixes the walkway. Design those relationships as carefully as the pump.' Molly writes the word agreement. It feels larger on the page than she expected. Beside her, a student draws a flowering balcony around a very competent plumbing diagram."),
                    P("DR. VALE", "Tomorrow, each student may be called on to explain a circulation plan. The task is small: three growing beds, one reservoir, a changing day. 'There may be several good approaches,' Vale says. 'Tell us what yours pays attention to.' Molly writes the deadline twice. Outside, lunch is beginning along the canal. There is still an afternoon to choose.")
                };
                case "study": return new List<StoryPage> {
                    P("THE READING ROOM", "Molly chooses the library table nearest the door. Preparing costs one afternoon slot and raises Pressure by 12, but the assignment will be ready tomorrow. On paper, the reservoir becomes a simple promise: water given to one bed is water unavailable to another. The plants do not all need the same amount. That is the point."),
                    P("MOLLY", "Her first drawing distributes water equally. It looks fair. Her second drawing gives each bed what its roots can actually use. It looks less symmetrical and works better. She leaves both in the notebook, with an arrow between them. Understanding something can feel like becoming less certain of your first answer, then more precise about the next."),
                    P("A NOTE FOR TOMORROW", "She writes: 'Observe need. Allocate the available supply. Observe again when conditions change.' Under it, she adds a question about shade. By the time she closes the book her shoulders ache, but the page exists. Tomorrow's answer will not have to be invented while everybody watches. You have gained Prepared; the map remembers that this activity is complete.")
                };
                case "social": return new List<StoryPage> {
                    P("THE CANAL STEPS", "A student has occupied three steps with a sandwich, a notebook, and a jacket that is somehow still dripping. 'Jules,' they say, shifting everything to make space. 'The canal and I had an introductory disagreement.' Molly laughs before she can plan how. Company takes one afternoon slot and eases Pressure by 9. There is no test to pass here."),
                    P("JULES", "'Someone asked if I'd already chosen a field,' Jules says. 'I said dry land.' They compare timetables. The same morning class. The same assignment. Jules is interested in public sound systems: messages people can understand when the city is loud. Molly admits she worries more about being heard than about what she might say."),
                    P("MOLLY", "Jules doesn't tell her there is nothing to worry about. They ask where she prefers to sit. 'Near the door,' Molly says, surprised by how easy the answer is. A boat turns beneath the bridge, carrying a whole tree in a pot. They watch it go without speaking. Tomorrow, one face in the room will already know hers.")
                };
                case "rest": return new List<StoryPage> {
                    P("THE RESIDENCE", "Rest takes one afternoon slot and eases Pressure by 17. Molly loosens the collar of her jacket and sets an ordinary kitchen timer. She doesn't have to make this time productive. Through the shutters, water taps a mooring post; a neighbor upstairs puts a record on, then changes their mind before the song has quite begun."),
                    P("MOLLY", "For a while she thinks about how much she could be doing. Eventually she notices the chair under her legs. Her shoulders begin to loosen. The hum in the brass fittings hasn't vanished, but other sounds have room beside it. She has been clenching her left hand without realizing. Now she recognizes that feeling a little earlier."),
                    P("A SMALL RETURN", "When the timer rings, she eats the toast she forgot this morning. On the sill, her chosen keepsake has collected a thin bar of afternoon light. Rest hasn't finished her assignment or introduced her to anyone. It has helped her return to a day that still contains choices. Tomorrow, that recognition will give her a moment to respond.")
                };
                case "night": return new List<StoryPage> {
                    P("THE FIRST NIGHT", "Lights gather in the windows across the canal. Somewhere below, a group of students tries to sing a song none of them quite remembers. Molly can identify her own room from the opposite bank now: the crooked shutter, the little object on the sill. The city has acquired one small point that means home."),
                    P("MOLLY", (s.studied ? "Her finished assignment waits beside the bed. " : "The assignment is still an outline. She can ask for help tomorrow. ") + (s.socialized ? "Jules has sent a drawing of an extremely displeased canal. " : "The corridor is full of voices she may get to know. ") + (s.rested ? "She remembers the shape her hand makes when she needs a pause. " : "She notices how tired her shoulders have become. ") + "The choices did not make a perfect day. They made this particular one."),
                    P("THE CLOCHE", "As she turns out the lamp, its filament briefly warms again. There is a low note in the window latch, too faint to call a sound. Across Halcyon, the storm-harvesting ribs catch distant weather. Molly watches until the glass is only glass. Tomorrow's Pressure will carry today's consequences, softened by sleep. Select Continue to turn the page into morning.")
                };
                case "morning2": return new List<StoryPage> {
                    P("DAY TWO", "Morning arrives with rain high above the dome and clean sunlight below it. The contradictory weather makes Molly smile until she remembers the classroom. Her keepsake is still on the sill. The room has become hers without asking permission. Only the residence is available on the map until she finishes getting ready, just as it was yesterday."),
                    P("MOLLY", "The familiar case waits beside her breakfast. She can keep her usual routine or leave it for this morning. Neither choice closes off the greenhouse or what she may notice there. Care can help without explaining everything she experiences. The barometer shows her current Pressure; the rest of the day is still allowed to surprise her.", C("Follow the familiar routine  ·  Pressure −6", "routine"), C("Put it away for this morning", "noroutine")),
                    P("WHAT YOU BRING WITH YOU", (s.studied ? "The three-branch diagram is folded into her notebook. She can explain why equal amounts would not be enough. " : "She has a question about the reservoir instead of a finished answer. Questions are allowed; she tries to remember that. ") + (s.socialized ? "Jules has saved the seat near the door. " : "She chooses a seat with a clear view of the door. ") + (s.rested ? "Before leaving, she uncurls her hand. She knows that sign now." : "She smooths her collar twice, then steps outside."))
                };
                case "class2": return new List<StoryPage> {
                    P("THE SECOND CLASS", "The model reservoir is running when Molly arrives. Sun moves across the three miniature beds. A valve ticks a little out of rhythm. Vale turns the attendance cards face down and draws one. There is a quiet movement through the room as everyone imagines their own name. 'Molly,' the lecturer says. 'Would you begin?'"),
                    P("MOLLY", s.studied ? "She gives the answer she prepared: the beds need different amounts, and the distribution must change with the light. Vale nods. 'Good. What would you need to know before making the same decision for an entire Ward?' The answer worked. The follow-up opens too many doors at once. Behind the glass, the model makes a note she feels in her teeth." : "She finds the beginning of an answer about the reservoir. The next sentence won't line up behind it. 'Take your time,' Vale says, gently. A valve taps against its housing. Under that sound is another, almost familiar. Molly looks down at her notebook and cannot find the place where her eyes have stopped."),
                    P("THE ROOM", "Her heart is racing. Her hand trembles against the page. She knows where she is, but the room feels distant, and drawing a full breath has become something she is trying too hard to do. The unfinished answer seems enormously loud. Pressure rises; the lesson is interrupted. This scene is not a failure, and it does not erase what you did yesterday.", C(s.rested ? "Recognize the signs and ask to step outside" : "Ask for a moment outside", "panic"), C(s.socialized ? "Look to Jules for help" : "Ask the lecturer for help", "support")),
                    P("A DOOR OPENS", s.socialized ? "Jules stands without making an announcement. 'I'll show you where the water is,' they say, giving Molly a practical reason to move. Vale makes space by the door. Nobody asks her to finish the sentence. The assignment is still there in the room; she can come back to it later. Right now, there is the corridor." : "Vale sets down the attendance card. 'Yes. Take the time you need.' Molly hears the words a second after they are spoken. She gets to her feet, steadies herself against the table, and leaves. No one needs an explanation at this instant. On the other side of the door, the sounds separate a little."),
                    P("MOLLY", "The corridor tiles are cool through her shoes. She counts the visible doors because they stay where they are. Water. Stairwell. A frosted pane with leaves moving behind it. The air leaking beneath that last door is warm and damp. The map has changed: the greenhouse is available. For now, demanding activities can wait. Find somewhere quieter.")
                };
                case "greenhouse": return new List<StoryPage> {
                    P("THE GREENHOUSE", "Water moves under the walkway in slow green sheets. Molly sits on a bench before she notices anybody else. Nobody has arranged this room around her arrival. A kettle clicks; a pump mutters; someone at the far table says, with considerable feeling, 'Oh, absolutely not,' to a very small plant. Molly's breathing begins to settle in its own uneven time."),
                    P("LOLA", "The student at the table turns. Brown curls are pinned high beneath a patterned scarf; the sleeve of her uniform is rolled almost to the elbow. 'You can sit there,' she says. 'The bench is structurally sound. My prototype has decided to become a swamp, so I can't make the same promise for this table.' She moves the kettle within reach."),
                    P("MOLLY", "'I'm Molly.' She waits for recognition to become the next thing she has to manage. 'Lola,' the other student says. 'Ninth Ward. And before you ask, yes, the plants do listen. They're just terrible at following instructions.' Molly almost laughs. The room has not cured anything. It has become a room where she doesn't have to conceal every pause.", C("Tell her class was difficult", "share"), C("Ask about the floating garden", "askgarden")),
                    P("LOLA", s.shared ? "'You don't have to tell me all of it,' Lola says. She pulls a second stool close enough to offer, far enough to refuse. 'And you don't have to be useful to stay.' After a while, Molly asks what the garden is for. Lola looks at it with the complicated affection people usually reserve for family." : "'A garden the people using it can actually look after,' Lola says. 'Food, flowers, a place to sit. If it needs an Academy engineer every time a valve sticks, I've built a very attractive dependency.' She looks at the little raft. 'Also, the flowers matter. People should get to want somewhere beautiful.'"),
                    P("LOLA'S WORK", "Lola wants the garden to travel home to the Ninth, where raised walkways connect kitchens, growing houses, and workshops. She has drawn a bench into the raft instead of using every inch for crops. 'Mémère says if nobody can sit down, nobody will stay to notice what needs fixing.' A tube slips loose. Lola catches it without looking."),
                    P("A SHARED PROBLEM", "Molly recognizes the three-bed model from class, changed into something someone might want to live beside. Here the roots are real. There are six measures of circulating water, and each bed has different needs. The valves are labeled; nothing needs to be guessed from color. 'Want to try the distribution?' Lola asks. 'We can change it as often as we like.'"),
                    P("MOLLY", "The faint note is still somewhere in the glass. Under it, water and leaves make a rhythm Molly can follow. She takes the offered seat. This is something her mentor's question can help with, and something Lola already knows far more about than she does. A useful beginning. Select Continue to work on the garden together.")
                };
                case "aftergarden": return new List<StoryPage> {
                    P("THE WATER FINDS ITS WAY", s.solved ? "The last valve turns. All three beds receive what they need, even after the shade shifts. Lola watches the little raft level itself, then lets out the breath she was holding. 'There. That is a thing we could teach someone else to fix.' Molly looks at their hands on the same workbench. Her morning answer has become part of somebody's afternoon." : "They leave a neat note beside the prototype: circulation needs another trial. Lola turns the pump down safely. 'That counts as learning what it needs,' she says. 'I'd rather find out here than on somebody's doorstep.' The garden remains unfinished, and the invitation to come back remains quite clear. Molly has not been asked to earn a place on the bench."),
                    P("MOLLY", "'Sometimes I hear the storm before the instruments change,' Molly says. The sentence arrives before she can make it more acceptable. Lola doesn't offer a diagnosis or a revelation. She glances at the glass and then back at Molly. 'Then we can write down what you hear. And what the instruments say. See what we notice.' It is a question they can share."),
                    P("LOLA", "'Tomorrow, I'm taking these seedlings down to the water,' Lola says. 'You could come, if you'd like.' There is no attendance card, and no correct way to accept. Molly can want the invitation without deciding everything it might become. Beyond the dome, the rain continues. Inside it, there is a place she now knows how to find.", C("I'd like that. See you tomorrow.", "return"), C("Could we start with tea?", "tea")),
                    P("A PLACE TO RETURN TO", "When Molly opens the map again, the greenhouse has a name and a color. It is no longer an anonymous shape at the edge of the Academy. The city contains the morning she had, the work still waiting, and someone she wants to see again. The first two days are complete. What happens next belongs to the larger Halcyon story.")
                };
            }
            return new List<StoryPage> { P("HALCYON", "Return to the map to continue.") };
        }
        public static string Background(string key)
        {
            if (key == "morning1" || key == "morning2" || key == "rest" || key == "night") return "dorm";
            if (key == "greenhouse" || key == "aftergarden") return "greenhouse";
            return key == "social" ? "map" : "academy";
        }
    }
}
